### ISSUE TITLE
`regcomp` implementation

### ISSUE THREAD

**Issue by voidbar** [robinrowe/libunistd#10]
Neither https://github.com/robinrowe/libunistd/blob/master/regex/regex.cpp nor https://github.com/robinrowe/libunistd/blob/master/regex/engine.cpp supply the implementation of `regcomp` defined here: https://github.com/robinrowe/libunistd/blob/master/regex/regex.h#L107.

Is this intentional?

**Comment by robinrowe** [comment]
Except for fork(), that is deliberately omitted in preference to threads, where Linux system calls are not implemented in libunistd it is simply for lack of time/interest. If CinePaint or some other Linux-based WIndows port I touch doesn't need a POSIX call implemented, I leave it as a stub to do later. As regex is in C++11 and later, if we did need it, I would try to wrap the C++ call in the C syntax.

**Comment by timwoj** [comment]
This can probably be closed after the above PR.
