### ISSUE TITLE
poll()'s counting seems to increment the pointer instead of the value

### ISSUE THREAD

**Issue by tankorsmash** [robinrowe/libunistd#2]
https://github.com/robinrowe/libunistd/blob/069d450a54d6f57d3acaadd38fe3b53c14b8c345/unistd/poll.h#L39

Simplified demo of what I think is happening: http://cpp.sh/9tyco

`*readerCount++` seems like it should be `(*readerCount)++` to increment the value, not the pointer. Same for `writerCount`. 

I used VS2013, but the cpp.sh snippet uses GCC 4.9.2.

**Comment by lucasrangit** [comment]
I agree with @tankorsmash . Same is true for `*writerCount++`.

Postfix `++` has higher precedence than dereference `*` so it's being evaluated as `*(readerCount++)` and `readerCount` is a pointer on the stack.

**Comment by robinrowe** [comment]
Fixed. Thanks for the bug report.
